spring:
  application:
    name: melhorconsulta-api
  data:
    mongodb:
      repositories.type: reactive
      uri: ${MONGO_URI}
      database: consulta
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

pag-fly:
  base-url: https://api.pagfly.com/v1/
  private-key: ${PAGFLY_PRIVATE_KEY}
  password: ${PAGFLY_PASSWORD}

credlink:
  base-url: https://consulta.confirmeonline.com.br
  user: ${CREDLINK_USER}
  password: ${CREDLINK_PASSWORD}
  sigla: ${CREDLINK_SIGLA}

jwt:
  secret: ${JWT_SECRET}
