name: CI/CD - Build & Push Backend Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Versão da imagem (ex: 1.2.3)"
        required: false

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache do Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/settings.gradle.kts', '**/build.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Obter versão automática
        id: version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION=${{ github.event.inputs.version }}
          else
            LAST_VERSION=$(git tag --sort=-v:refname | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n 1)

            if [[ -z "$LAST_VERSION" ]]; then
              VERSION="1.0.0"
            else
              IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST_VERSION"
              PATCH=$((PATCH + 1))
              VERSION="$MAJOR.$MINOR.$PATCH"
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Versão definida: $VERSION"

      - name: Criar tag no repositório (se ainda não existir)
        run: |
          if git rev-parse "v${{ env.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.version }} já existe. Pulando criação."
          else
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git tag v${{ env.version }}
            git push origin v${{ env.version }}
          fi

      - name: Construir e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:latest
            ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:v${{ env.version }}
