name: BuildManually

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Tag Image version. ex: 0.0.1'     
        required: true
        default: '0.0.1'

jobs:
  BuildDockerImage:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que todo o histórico Git seja clonado

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2  # Atualizado para v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # Usa o token secreto criado no GitHub

      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4  # Atualizado para v4
        with:
          push: true
          no-cache: false
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:latest
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:${{ github.event.inputs.imageVersion }}
            ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:latest

      - name: Show Image Digest
        run: |
          echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
