name: BuildManually

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Tag Image version. ex: 0.0.1'     
        required: true
        default: '0.0.1'

jobs:
  BuildDockerImage:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todo o histórico Git seja clonado

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:${{ github.event.inputs.imageVersion }}
            ghcr.io/${{ github.repository_owner }}/melhorconsulta-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
