name: BuildManually

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Tag Image version. ex: 0.0.1'     
        required: true
        default: '0.0.1'

jobs:
  BuildDockerImage:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que todo o histórico Git seja clonado

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io  # Certifique-se de usar o correto (Docker Hub)
          username: ${{ secrets.DOCKER_USERNAME }}  # Alterado para usar credencial segura
          password: ${{ secrets.DOCKER_PASSWORD }}  # Criar um Secret no GitHub Actions

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          no-cache: false  # Cache ativado para acelerar builds
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/melhorconsulta-api:${{ github.event.inputs.imageVersion }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/melhorconsulta-api:latest

      - name: Show Image Digest
        run: |
          echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
